# Generated by Django 6.0.3 on 2026-03-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.SmallIntegerField()),
                ('device_id', models.CharField(max_length=32)),
                ('sequence', models.IntegerField()),
                ('timeData', models.CharField(max_length=8)),
                ('dateData', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pressure', models.IntegerField()),
                ('co2', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('ethylene', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-dateData'],
                'indexes': [models.Index(fields=['device_id', 'dateData'], name='devices_sen_device__506b6d_idx'), models.Index(fields=['-dateData'], name='devices_sen_dateDat_695848_idx')],
            },
        ),
    ]
