# Generated by Django 6.0.3 on 2026-03-31 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_sensorreading'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sensorreading',
            name='devices_sen_device__506b6d_idx',
        ),
        migrations.RemoveIndex(
            model_name='sensorreading',
            name='devices_sen_dateDat_695848_idx',
        ),
        migrations.DeleteModel(
            name='SensorReading',
        ),
    ]
