# Generated by Django 6.0.3 on 2026-06-03 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_remove_sensorreading_devices_sen_device__506b6d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('executed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='devices.device')),
            ],
            options={
                'db_table': 'device_commands',
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.PositiveSmallIntegerField()),
                ('sequence', models.PositiveIntegerField()),
                ('timeData', models.TimeField()),
                ('dateData', models.DateTimeField()),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('co2', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('ethylene', models.CharField(blank=True, max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.device')),
            ],
            options={
                'db_table': 'sensor_readings',
                'managed': True,
            },
        ),
    ]
