# Generated by Django 6.0.3 on 2026-06-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_devicecommand_sensorreading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicecommand',
            name='device',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='device',
        ),
        migrations.AddField(
            model_name='devicecommand',
            name='device_id',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='device_id',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
